# -*- coding: utf-8 -*-
# Loom: Weaving the mathematics of light in thin film systems
# Copyright (c) 2026 opticsWolf
#
# SPDX-License-Identifier: LGPL-3.0-or-later

[pytest]
testpaths = validation
pythonpath = src
# Optional: display console output for performance metrics
addopts = -v --tb=short
